pipelines: 
  - name: zerobug
    steps:
      - name: curl
        type: Bash
        execution:
          onExecute:
            - 'curl -k -u ${ZEROBUGUID}:${ZEROBUGTOKEN} --request POST -H "Content-Type:application/json" -d "{\"pit\":\"131\",\"targetid\":\"AyIX0lpNwZxAtbwjtRZX1598894821\",\"ci\":\"JFRog\",\"tipo\":\"12\"}" https://zerobug.co/ScanTarget/'
