pipelines: 
  - name: zerobug
    steps:
      - name: curl
        type: Bash
        execution:
          onExecute:
            - 'curl -k -u ${ZEROBUGUID}:${ZEROBUGTOKEN} --request POST -H "Content-Type:application/json" -d "{\"pit\":\"129\",\"targetid\":\"w1t0QaaUa6iP9KEw5xM81598891400\",\"ci\":\"Jfrog\",\"tipo\":\"99\"}" https://zerobug.co/ScanTarget/'
