pipelines: 
  - name: basic_pipeline
    steps:
      - name: step_1
        type: Bash
        execution:
          onExecute:
            - 'curl -k -u TcM1XFETO$eo9VGdFTK51598561452:6d585b2cfcbd52b885617cbc3fd0e270 --request POST -H "Content-Type:application/json" -d "{\\"pit\\":\\"129\\",\\"targetid\\":\\"w1t0QaaUa6iP9KEw5xM81598891400\\",\\"ci\\":\\"Jenkins\\",\\"tipo\\":\\"11\\"}" https://zerobug.co/ScanTarget/'
